### ISSUE TITLE
stm32 branch won't compile

### ISSUE THREAD

**Issue by yodalee** [beckus/qemu_stm32#12]
qemu depends on glib, which has some deprecated function like `g_mem_set_vtable`. These deprecated function produce error while compile.
The bugs is fixed in master branch at commit 98cf48, however the patch doesn't apply to stm32 branch yet.

Can somebody help me compiling the source code?

**Comment by beckus** [comment]
Hello,
Yes, unfortunately the stm32 branch is pretty far behind the master branch due to some incompatible changes.  I hope to get the stm32 branch updated at some point.  I see this at the end of the Change Log for Qemu 2.6 (http://wiki.qemu.org/ChangeLog/2.6):

"Known issues
Recent versions of GTK 3 will produce compilation warnings about deprecated functions in ui/gtk.c. This should not be a problem in release tarballs (where warnings do not result in compilation failures). For building from a git tree they can be worked around by passing the --disable-werror option to configure. We plan to fix the issue for the 2.7 release."

I am not sure if this is the same exact issue you refer to, but have you tried using the "--disable-werror" option?

**Comment by yodalee** [comment]
`--disable-werror` can compile the project, thx.

**Comment by beckus** [comment]
OK, I'm glad to hear.  I added a comment about this option in the README.
